name: setup-viennals
description: Setup ViennaLS
inputs:
  path:
    description: directory where the action should be executed
    required: true
  build_type:
    description: CMake build type (Release, Debug, RelWithDebInfo, etc.)
    required: false
    default: Debug
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ViennaTools/ViennaLS
        path: ${{inputs.path}}
        ref: master

    - name: Setup Cache for Build Dependencies
      uses: actions/cache@v3
      id: cache-dependencies
      with:
        key: viennals-dependencies-cache-${{ runner.os }}-${{ hashFiles(inputs.path + '/viennals/external/upstream/**CMakeLists.txt') }}
        path: |
          ${{inputs.path}}/dependencies/Build
          ${{inputs.path}}/dependencies/Install

    - if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
      name: Configure ViennaLS
      shell: bash
      working-directory: ${{inputs.path}}
      run: |
        cmake -B ${{inputs.path}}/build \
          -DCMAKE_BUILD_TYPE=${{inputs.build_type}} \
          -DCMAKE_INSTALL_PREFIX=${{inputs.path}}/install

    - if: ${{ steps.cache-dependencies.outputs.cache-hit == 'true' }}
      name: Configure ViennaLS (cached dependencies)
      shell: bash
      run: |
        cmake -B ${{inputs.path}}/build \
          -DCMAKE_BUILD_TYPE=${{inputs.build_type}} \
          -DVTK_DIR=${{inputs.path}}/dependencies/Build/vtk_external/ \
          -DViennaHRLE_DIR=${{inputs.path}}/dependencies/Install/viennahrle_external/lib/cmake/ViennaHRLE/ \
          -DCMAKE_INSTALL_PREFIX=${{inputs.path}}/install

    - name: Build ViennaLS
      shell: bash
      working-directory: ${{inputs.path}}
      run: cmake --build ${{inputs.path}}/build --target buildDependencies all

    - name: Install ViennaLS
      shell: bash
      working-directory: ${{inputs.path}}
      run: cmake --install ${{inputs.path}}/build
