name: setup-viennals
description: Setup ViennaLS
inputs:
  build_type:
    description: CMake build type (Release, Debug, RelWithDebInfo, etc.)
    required: false
    default: Debug
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ViennaTools/ViennaLS
        path: viennals

    - name: Setup Cache for Build Dependencies
      uses: actions/cache@v3
      id: cache-dependencies
      with:
        key: viennals-dependencies-cache-${{ runner.os }}-${{ hashFiles('./viennals/external/upstream/**CMakeLists.txt') }}
        path: |
          ${{github.workspace}}/viennals/dependencies/Install

    - if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
      name: Configure ViennaLS
      shell: bash
      run: |
        cmake -B ${{github.workspace}}/viennals/build \
          -DCMAKE_BUILD_TYPE=${{inputs.build_type}} \
          -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/viennals/install

    - if: ${{ steps.cache-dependencies.outputs.cache-hit == 'true' }}
      name: Configure ViennaLS (cached dependencies)
      shell: bash
      run: |
        cmake -B ${{github.workspace}}/viennals/build \
          -DCMAKE_BUILD_TYPE=${{inputs.build_type}} \
          -DVTK_DIR=${{github.workspace}}/viennals/dependencies/Install/vtk_external/lib/cmake/vtk-9.1/ \
          -DViennaHRLE_DIR=${{github.workspace}}/viennals/dependencies/Install/viennahrle_external/lib/cmake/ViennaHRLE/ \
          -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/viennals/install

    - name: Build ViennaLS
      shell: bash
      run: cmake --build ${{github.workspace}}/viennals/build --target buildDependencies all

    - name: Install ViennaLS
      shell: bash
      run: cmake --install ${{github.workspace}}/viennals/build
