name: setup-viennaray
description: Setup ViennaRay
inputs:
  path:
    description: directory where the action should be executed
    required: true
  build_type:
    description: CMake build type (Release, Debug, RelWithDebInfo, etc.)
    required: false
    default: Debug
runs:
  using: composite
  steps:
    - name: Clone ViennaRay
      uses: actions/checkout@v3
      with:
        repository: ViennaTools/ViennaRay
        path: ${{inputs.path}}

    - name: Setup Cache for Build Dependencies
      uses: actions/cache@v3
      id: cache-dependencies
      with:
        key: viennaray-dependencies-cache-${{ runner.os }}-${{ hashFiles( format('{0}/external/upstream/**CMakeLists.txt', inputs.path) ) }}
        path: |
          ${{inputs.path}}/dependencies/Install

    - if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
      name: Configure ViennaRay
      shell: bash
      working-directory: ${{inputs.path}}
      run: |
        cmake -B ${{inputs.path}}/build \
          -DCMAKE_BUILD_TYPE=${{inputs.build_type}} \
          -DCMAKE_INSTALL_PREFIX=${{inputs.path}}/install

    - if: ${{ steps.cache-dependencies.outputs.cache-hit == 'true' }}
      name: Configure ViennaRay (cached dependencies)
      shell: bash
      run: |
        cmake -B ${{inputs.path}}/build \
          -DCMAKE_BUILD_TYPE=${{inputs.build_type}} \
          -Dembree_DIR=${{inputs.path}}/dependencies/Install/embree_external/ \
          -DCMAKE_INSTALL_PREFIX=${{inputs.path}}/install

    - name: Build ViennaRay
      shell: bash
      working-directory: ${{inputs.path}}
      run: cmake --build ${{inputs.path}}/build --target buildDependencies all

    - name: Install ViennaRay
      shell: bash
      working-directory: ${{inputs.path}}
      run: cmake --install ${{inputs.path}}/build
