name: Check If Cache Item Exists
description: Checks if the the cache item with the provided key exists
inputs:
  cache-key:
    description: Cache key
    required: true
  token:
    description: The Personal access token for the github API endpoint
    required: true
  repository:
    description: The repository "username/repo"
    required: true
outputs:
  cache-hit:
    description: "Whether the provided key exists or not"
    value: ${{ steps.check.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - shell: bash
      run: echo ${{inputs.cache-key}}

    - id: check
      shell: bash
      run: |
        python3 - <<EOF
        import requests
        import json

        url = "https://api.github.com/repos/${{inputs.repository}}/actions/caches"
        ret = requests.post(url, headers={"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ inputs.token }}"})

        ret = ret.json()

        cache_list = ret["actions_caches"]
        cache_keys = [e["key"] for e in cache_list]
        if len(list(filter(lambda e: e == "${{inputs.cache-key}}"", cache_keys))) > 0:
          print("cache-hit=true")
        else:
          print("cache-hit=false")
        EOF >> $GITHUB_OUTPUT
