name: Linux

on:
  push:
    branches: [actions]
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: viennaps

      - uses: ./viennaps/.github/setup-viennals/
        with:
          path: ${{github.workspace}}/viennals/
          build_type: Debug

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/viennaps/build \
            -DViennaLS_DIR=${{github.workspace}}/viennals/install/lib/cmake/ViennaLS/

      - name: print folders
        run: tree -d ${{github.workspace}}/viennals

      # - name: Build Dependencies
      #   run: cmake --build ${{github.workspace}}/build --target buildDependencies

      # - name: Enable Examples Target
      #   run: cmake -B ${{github.workspace}}/build -DVIENNAPS_BUILD_EXAMPLES=ON

      # - name: Build Examples
      #   run: cmake --build ${{github.workspace}}/build

      # - name: Run
      #   working-directory: ${{github.workspace}}/build
      #   run: ./Examples/InterpolationDemo/InterpolationDemo
