name: Linux

on:
  push:
    branches: [actions]
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone ViennaPS
        uses: actions/checkout@v3

      - name: Setup ViennaLS
        uses: ./.github/setup-viennals/
        with:
          path: ${{github.workspace}}/viennals/
          build_type: Debug

      - name: Setup ViennaRay
        uses: ./.github/setup-viennaray/
        with:
          path: ${{github.workspace}}/viennaray/
          build_type: Debug

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
            -DViennaLS_DIR=${{github.workspace}}/viennals/install/lib/cmake/ViennaLS/ \
            -DViennaRay_DIR=${{github.workspace}}/viennaray/install/lib/cmake/ViennaRay/

      - name: print folders
        run: |
          tree -d ${{github.workspace}}/viennals
          tree -d ${{github.workspace}}/viennaray

      - name: Build Dependencies
        run: cmake --build ${{github.workspace}}/build --target buildDependencies

      - name: Enable Examples Target
        run: cmake -B ${{github.workspace}}/build -DVIENNAPS_BUILD_EXAMPLES=ON

      - name: Build Examples
        run: cmake --build ${{github.workspace}}/build --target buildExamples

      - name: Run
        working-directory: ${{github.workspace}}/build/Examples/InterpolationDemo
        run: ./InterpolationDemo
