name: Linux

on:
  push:
      branches: [ actions ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: ./github/setup-action
        with:
          build_type: Debug

      - name: Enable Examples Target
        run: |
          cmake -B ${{github.workspace}}/build -DVIENNAPS_BUILD_EXAMPLES=ON

      - name: Build examples
        run: cmake --build ${{github.workspace}}/build

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          ./Examples/InterpolationDemo/InterpolationDemo
