name: Test step output

on:
  workflow_dispatch:

jobs:
  setup-viennals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ViennaPS
        uses: actions/checkout@v3

      - name: Run command
        id: run-command
        run: |
          export EXISTS=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PAT_CACHE }}" https://api.github.com/repos/yozoon/ViennaPS/actions/caches | jq -r '.actions_caches|any(.key == "A")') && echo "cache-hit=$EXISTS" >> $GITHUB_OUTPUT

      - name: Print command output
        run: |
          echo ${{steps.run-command.outputs.hit}}
